unit_reference_data = [
    {'Group': 'NYW', 'Unit Name': 'NY Wing HQ Squadron, inactive', 'Unit Type': 'comp', 'Unit Number': 'NY-000'},
    {'Group': 'NYW', 'Unit Name': 'New York State Legislative Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-999'},
    {'Group': 'CMG', 'Unit Name': 'Catskill Mountain Group', 'Unit Type': 'group', 'Unit Number': 'NY-035'},
    {'Group': 'CMG', 'Unit Name': 'Orange County Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-030'},
    {'Group': 'CMG', 'Unit Name': 'Rockland Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-072'},
    {'Group': 'CMG', 'Unit Name': 'Dutchess County Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-159'},
    {'Group': 'CMG', 'Unit Name': 'Sullivan County Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-387'},
    {'Group': 'CMG', 'Unit Name': 'Ulster County Flight', 'Unit Type': 'flight', 'Unit Number': 'NY-395'},
    {'Group': 'CMG', 'Unit Name': 'Orange County Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-413'},
    {'Group': 'CMG', 'Unit Name': 'Dutchess County Senior', 'Unit Type': 'flight*', 'Unit Number': 'NY-421'},
    {'Group': 'CNY', 'Unit Name': 'Central New York Group', 'Unit Type': 'group', 'Unit Number': 'NY-134'},
    {'Group': 'CNY', 'Unit Name': 'Lt Col William J. Shafer Cadet', 'Unit Type': 'cadet', 'Unit Number': 'NY-135'},
    {'Group': 'CNY', 'Unit Name': 'Mohawk Griffiss Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-156'},
    {'Group': 'CNY', 'Unit Name': 'Utica Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-162'},
    {'Group': 'CNY', 'Unit Name': 'Tri-County Flight', 'Unit Type': 'flight', 'Unit Number': 'NY-189'},
    {'Group': 'CNY', 'Unit Name': 'Southern Tier Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-292'},
    {'Group': 'CNY', 'Unit Name': 'Fort Drum Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-406'},
    {'Group': 'CNY', 'Unit Name': 'F.R. Sussey Composite Squadron, Fulton', 'Unit Type': 'comp', 'Unit Number': 'NY-408'},
    {'Group': 'FLG', 'Unit Name': 'Finger Lakes Group', 'Unit Type': 'group', 'Unit Number': 'NY-109'},
    {'Group': 'FLG', 'Unit Name': 'Newark Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-111'},
    {'Group': 'FLG', 'Unit Name': 'Canandaigua Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-212'},
    {'Group': 'FLG', 'Unit Name': 'Batavia Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-253'},
    {'Group': 'FLG', 'Unit Name': 'Rochester Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-273'},
    {'Group': 'FLG', 'Unit Name': 'Twin Tiers Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-283'},
    {'Group': 'FLG', 'Unit Name': 'Condor Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-354'},
    {'Group': 'FLG', 'Unit Name': 'Rochester Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-412'},
    {'Group': 'LIG', 'Unit Name': 'Long Island Group', 'Unit Type': 'group', 'Unit Number': 'NY-251'},
    {'Group': 'LIG', 'Unit Name': 'Col Francis S. Gabreski Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-117'},
    {'Group': 'LIG', 'Unit Name': 'Leroy R. Grumman Cadet Squadron ', 'Unit Type': 'cadet', 'Unit Number': 'NY-153'},
    {'Group': 'LIG', 'Unit Name': 'Long Island Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-207'},
    {'Group': 'LIG', 'Unit Name': 'Brian M. Mooney Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-247'},
    {'Group': 'LIG', 'Unit Name': 'Lt Quentin Roosevelt Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-288'},
    {'Group': 'LIG', 'Unit Name': '9th Suffolk Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-311'},
    {'Group': 'LIG', 'Unit Name': 'Suffolk Cadet Squadron 10 ', 'Unit Type': 'cadet', 'Unit Number': 'NY-328'},
    {'Group': 'LIG', 'Unit Name': 'The Spirit of Tuskegee Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-332'},
    {'Group': 'MEG', 'Unit Name': 'Mid-Eastern Group', 'Unit Type': 'group', 'Unit Number': 'NY-043'},
    {'Group': 'MEG', 'Unit Name': 'Schenectady Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-073'},
    {'Group': 'MEG', 'Unit Name': 'Albany Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-361'},
    {'Group': 'MEG', 'Unit Name': 'James P O'Connor Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-388'},
    {'Group': 'MEG', 'Unit Name': 'Vanguard Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-390'},
    {'Group': 'MEG', 'Unit Name': 'Vedder Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-392'},
    {'Group': 'MEG', 'Unit Name': 'Capt Luke C. Wullenwaber Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-415'},
    {'Group': 'NYCG', 'Unit Name': 'New York City Group', 'Unit Type': 'group', 'Unit Number': 'NY-015'},
    {'Group': 'NYCG', 'Unit Name': 'Bronx Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-089'},
    {'Group': 'NYCG', 'Unit Name': 'Academy Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-147'},
    {'Group': 'NYCG', 'Unit Name': 'Phoenix Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-301'},
    {'Group': 'NYCG', 'Unit Name': 'Floyd Bennett Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-373'},
    {'Group': 'NYCG', 'Unit Name': 'Falcon Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-379'},
    {'Group': 'NYCG', 'Unit Name': 'Brooklyn Tech Cadet Squadron #1', 'Unit Type': 'cadet', 'Unit Number': 'NY-384'},
    {'Group': 'NYCG', 'Unit Name': 'Lt Vincent R. Capodanno Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-420'},
    {'Group': 'NYCG', 'Unit Name': 'Bronx Aerospace Cadet Flight', 'Unit Type': 'flight', 'Unit Number': 'NY-423'},
    {'Group': 'NYCG', 'Unit Name': 'Brooklyn Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-613'},
    {'Group': 'WNY', 'Unit Name': 'Western New York', 'Unit Type': 'group', 'Unit Number': 'NY-024'},
    {'Group': 'WNY', 'Unit Name': 'Southtowns Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-020'},
    {'Group': 'WNY', 'Unit Name': 'Buffalo Composite Squadron #1', 'Unit Type': 'comp', 'Unit Number': 'NY-022'},
    {'Group': 'WNY', 'Unit Name': 'Niagara Falls Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-116'},
    {'Group': 'WNY', 'Unit Name': 'TAK Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-173'},
    {'Group': 'WNY', 'Unit Name': 'Niagara Frontier Senior Squadron', 'Unit Type': 'flight', 'Unit Number': 'NY-343'},
    {'Group': 'WNY', 'Unit Name': 'Dunkirk Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-351'},
    {'Group': 'WNY', 'Unit Name': 'Jamestown Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-402'},
    {'Group': 'WNY', 'Unit Name': 'Buffalo Creek Academy Cadet Sq', 'Unit Type': 'cadet', 'Unit Number': 'NY-824'},
    {'Group': 'SEG', 'Unit Name': 'South Eastern Group', 'Unit Type': 'group', 'Unit Number': 'NY-118'},
    {'Group': 'SEG', 'Unit Name': 'Putnam County Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-033'},
    {'Group': 'SEG', 'Unit Name': 'Westchester Cadet Squadron 1', 'Unit Type': 'cadet', 'Unit Number': 'NY-048'},
    {'Group': 'SEG', 'Unit Name': 'Westchester Hudson Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-219'},
    {'Group': 'SEG', 'Unit Name': 'Col Johnnie Pantanelli Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-238'},
    {'Group': 'SEG', 'Unit Name': 'Lt Anthony L. Willsea Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-422'},
]