unit_reference_data = [
    {'Group': None, 'Unit Name': 'NY Wing HQ Squadron, inactive', 'Unit Type': 'comp', 'Unit Number': 'NY-000'},
    {'Group': None, 'Unit Name': 'New York State Legislative Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-999'},
    {'Group': 'CMG', 'Unit Name': 'Catskill Mountain Group', 'Unit Type': 'group', 'Unit Number': 'NY-035'},
    {'Group': 'CMG', 'Unit Name': 'Orange County Cadet', 'Unit Type': 'cadet', 'Unit Number': 'NY-030'},
    {'Group': 'CMG', 'Unit Name': 'Rockland Cadet', 'Unit Type': 'cadet', 'Unit Number': 'NY-072'},
    {'Group': 'CMG', 'Unit Name': 'Dutchess County Cadet', 'Unit Type': 'cadet', 'Unit Number': 'NY-159'},
    {'Group': 'CMG', 'Unit Name': 'Sullivan County ', 'Unit Type': 'cadet', 'Unit Number': 'NY-387'},
    {'Group': 'CMG', 'Unit Name': 'Ulster County Flight (to NY-030)', 'Unit Type': 'flight', 'Unit Number': 'NY-395'},
    {'Group': 'CMG', 'Unit Name': 'Orange County Senior*', 'Unit Type': 'senior', 'Unit Number': 'NY-413'},
    {'Group': 'CMG', 'Unit Name': 'Dutchess County Senior (to NY-413)', 'Unit Type': 'flight*', 'Unit Number': 'NY-421'},
    {'Group': 'CMG', 'Unit Name': 'Central New York Group', 'Unit Type': 'group', 'Unit Number': 'NY-134'},
    {'Group': 'CMG', 'Unit Name': 'Lt Col William J. Shafer Cadet', 'Unit Type': 'cadet', 'Unit Number': 'NY-135'},
    {'Group': 'CMG', 'Unit Name': 'Mohawk Griffiss Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-156'},
    {'Group': 'CMG', 'Unit Name': 'Utica Cadet Squadron        (Rome)', 'Unit Type': 'cadet', 'Unit Number': 'NY-162'},
    {'Group': 'CMG', 'Unit Name': 'Tri-County Flight **', 'Unit Type': 'flight', 'Unit Number': 'NY-189'},
    {'Group': 'CMG', 'Unit Name': 'Southern Tier Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-292'},
    {'Group': 'CMG', 'Unit Name': 'Fort Drum Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-406'},
    {'Group': 'CMG', 'Unit Name': 'F.R. Sussey Composite Squadron, Fulton', 'Unit Type': 'comp', 'Unit Number': 'NY-408'},
    {'Group': 'CMG', 'Unit Name': 'Finger Lakes Group', 'Unit Type': 'group', 'Unit Number': 'NY-109'},
    {'Group': 'CMG', 'Unit Name': 'Newark Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-111'},
    {'Group': 'CMG', 'Unit Name': 'Canandaigua Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-212'},
    {'Group': 'CMG', 'Unit Name': 'Batavia Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-253'},
    {'Group': 'CMG', 'Unit Name': 'Rochester Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-273'},
    {'Group': 'CMG', 'Unit Name': 'Twin Tiers Cadet (Chemung/Schuyler)', 'Unit Type': 'cadet', 'Unit Number': 'NY-283'},
    {'Group': 'CMG', 'Unit Name': 'Condor', 'Unit Type': 'comp', 'Unit Number': 'NY-354'},
    {'Group': 'CMG', 'Unit Name': 'Rochester Senior', 'Unit Type': 'senior', 'Unit Number': 'NY-412'},
    {'Group': 'CMG', 'Unit Name': 'Long Island Group', 'Unit Type': 'group', 'Unit Number': 'NY-251'},
    {'Group': 'CMG', 'Unit Name': 'Col Francis S. Gabreski', 'Unit Type': 'cadet', 'Unit Number': 'NY-117'},
    {'Group': 'CMG', 'Unit Name': 'Leroy R. Grumman Cadet Squadron ', 'Unit Type': 'cadet', 'Unit Number': 'NY-153'},
    {'Group': 'CMG', 'Unit Name': 'Long Island Senior', 'Unit Type': 'senior', 'Unit Number': 'NY-207'},
    {'Group': 'CMG', 'Unit Name': 'Brian M. Mooney', 'Unit Type': 'cadet', 'Unit Number': 'NY-247'},
    {'Group': 'CMG', 'Unit Name': 'Lt Quentin Roosevelt Cadet', 'Unit Type': 'cadet', 'Unit Number': 'NY-288'},
    {'Group': 'CMG', 'Unit Name': '9th Suffolk Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-311'},
    {'Group': 'CMG', 'Unit Name': 'Suffolk Cadet Squadron 10 ', 'Unit Type': 'cadet', 'Unit Number': 'NY-328'},
    {'Group': 'CMG', 'Unit Name': 'The Spirit of Tuskegee', 'Unit Type': 'cadet', 'Unit Number': 'NY-332'},
    {'Group': 'MEG', 'Unit Name': 'Mid-Eastern Group', 'Unit Type': 'group', 'Unit Number': 'NY-043'},
    {'Group': 'MEG', 'Unit Name': 'Schenectady Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-073'},
    {'Group': 'MEG', 'Unit Name': 'Albany Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-361'},
    {'Group': 'MEG', 'Unit Name': "James P. O'Conner Composite", 'Unit Type': 'comp', 'Unit Number': 'NY-388'},
    {'Group': 'MEG', 'Unit Name': 'Vanguard Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-390'},
    {'Group': 'MEG', 'Unit Name': 'Vedder Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-392'},
    {'Group': 'MEG', 'Unit Name': 'Capt Luke C. Wullenwaber Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-415'},
    {'Group': 'MEG', 'Unit Name': 'New York City Group', 'Unit Type': 'group', 'Unit Number': 'NY-015'},
    {'Group': 'MEG', 'Unit Name': 'Bronx Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-089'},
    {'Group': 'MEG', 'Unit Name': 'Academy', 'Unit Type': 'cadet', 'Unit Number': 'NY-147'},
    {'Group': 'MEG', 'Unit Name': 'Phoenix', 'Unit Type': 'comp', 'Unit Number': 'NY-301'},
    {'Group': 'MEG', 'Unit Name': 'Southern Tier Flight  (deactivated 22Jun)', 'Unit Type': 'flight', 'Unit Number': 'NY-414'},
    {'Group': 'MEG', 'Unit Name': 'Floyd Bennett', 'Unit Type': 'comp', 'Unit Number': 'NY-373'},
    {'Group': 'MEG', 'Unit Name': 'Falcon Senior', 'Unit Type': 'senior', 'Unit Number': 'NY-379'},
    {'Group': 'MEG', 'Unit Name': 'Brooklyn Tech Cadet Squadron #1', 'Unit Type': 'cadet', 'Unit Number': 'NY-384'},
    {'Group': 'MEG', 'Unit Name': 'Lt Vincent R. Capodanno Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-420'},
    {'Group': 'MEG', 'Unit Name': 'Bronx Aerospace Cadet Flight', 'Unit Type': 'flight', 'Unit Number': 'NY-423'},
    {'Group': 'MEG', 'Unit Name': 'Brooklyn Senior Squadron', 'Unit Type': 'senior', 'Unit Number': 'NY-613'},
    {'Group': 'MEG', 'Unit Name': 'Western New York', 'Unit Type': 'group', 'Unit Number': 'NY-024'},
    {'Group': 'MEG', 'Unit Name': 'Southtowns Cadet Squadron', 'Unit Type': 'cadet', 'Unit Number': 'NY-020'},
    {'Group': 'MEG', 'Unit Name': 'Buffalo Composite Squadron #1', 'Unit Type': 'comp', 'Unit Number': 'NY-022'},
    {'Group': 'MEG', 'Unit Name': 'Niagara Falls Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-116'},
    {'Group': 'MEG', 'Unit Name': 'TAK Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-173'},
    {'Group': 'MEG', 'Unit Name': 'Niagara Frontier Senior Squadron', 'Unit Type': 'flight', 'Unit Number': 'NY-343'},
    {'Group': 'MEG', 'Unit Name': 'Dunkirk Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-351'},
    {'Group': 'MEG', 'Unit Name': 'Jamestown Composite Squadron', 'Unit Type': 'comp', 'Unit Number': 'NY-402'},
    {'Group': 'MEG', 'Unit Name': 'Buffalo Creek Academy Cadet Sq', 'Unit Type': 'cadet', 'Unit Number': 'NY-824'},
    {'Group': 'MEG', 'Unit Name': 'South Eastern Group', 'Unit Type': 'group', 'Unit Number': 'NY-118'},
    {'Group': 'MEG', 'Unit Name': 'Putnam County Composite', 'Unit Type': 'comp', 'Unit Number': 'NY-033'},
    {'Group': 'MEG', 'Unit Name': 'Westchester Cadet Squadron 1', 'Unit Type': 'cadet', 'Unit Number': 'NY-048'},
    {'Group': 'MEG', 'Unit Name': 'Westchester Hudson Senior', 'Unit Type': 'senior', 'Unit Number': 'NY-219'},
    {'Group': 'MEG', 'Unit Name': 'Col Johnnie Pantanelli Composite ', 'Unit Type': 'comp', 'Unit Number': 'NY-238'},
    {'Group': 'MEG', 'Unit Name': 'Lt Anthony L. Willsea Cadet ', 'Unit Type': 'cadet', 'Unit Number': 'NY-422'},
]